/*
 * Gym
 * A set of workout centric endpoints
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.Movement;
import io.swagger.v3.oas.annotations.media.Schema;

import javax.annotation.processing.Generated;
import java.io.IOException;
/**
 * Action performed to achieve athletic goals with its properties
 */
@Schema(description = "Action performed to achieve athletic goals with its properties")
@Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-01-02T14:46:21.450061375Z[GMT]")

public class Exercise {
  @SerializedName("movement")
  private Movement movement = null;

  @SerializedName("restPeriod")
  private Object restPeriod = null;

  @SerializedName("sets")
  private Object sets = null;

  @SerializedName("comment")
  private Object comment = null;

  public Exercise movement(Movement movement) {
    this.movement = movement;
    return this;
  }

   /**
   * Get movement
   * @return movement
  **/
  @Schema(description = "")
  public Movement getMovement() {
    return movement;
  }

  public void setMovement(Movement movement) {
    this.movement = movement;
  }

  public Exercise restPeriod(Object restPeriod) {
    this.restPeriod = restPeriod;
    return this;
  }

   /**
   * Get restPeriod
   * @return restPeriod
  **/
  @Schema(description = "")
  public Object getRestPeriod() {
    return restPeriod;
  }

  public void setRestPeriod(Object restPeriod) {
    this.restPeriod = restPeriod;
  }

  public Exercise sets(Object sets) {
    this.sets = sets;
    return this;
  }

   /**
   * List of attemps performing the exercise
   * @return sets
  **/
  @Schema(description = "List of attemps performing the exercise")
  public Object getSets() {
    return sets;
  }

  public void setSets(Object sets) {
    this.sets = sets;
  }

  public Exercise comment(Object comment) {
    this.comment = comment;
    return this;
  }

   /**
   * Feelings noticed after completion of a movement
   * @return comment
  **/
  @Schema(description = "Feelings noticed after completion of a movement")
  public Object getComment() {
    return comment;
  }

  public void setComment(Object comment) {
    this.comment = comment;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Exercise exercise = (Exercise) o;
    return Objects.equals(this.movement, exercise.movement) &&
        Objects.equals(this.restPeriod, exercise.restPeriod) &&
        Objects.equals(this.sets, exercise.sets) &&
        Objects.equals(this.comment, exercise.comment);
  }

  @Override
  public int hashCode() {
    return Objects.hash(movement, restPeriod, sets, comment);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Exercise {\n");
    
    sb.append("    movement: ").append(toIndentedString(movement)).append("\n");
    sb.append("    restPeriod: ").append(toIndentedString(restPeriod)).append("\n");
    sb.append("    sets: ").append(toIndentedString(sets)).append("\n");
    sb.append("    comment: ").append(toIndentedString(comment)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
