/*
 * Gym
 * A set of workout centric endpoints
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;

import javax.annotation.processing.Generated;
import java.io.IOException;
/**
 * Information about completed workout
 */
@Schema(description = "Information about completed workout")
@Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-01-02T14:46:21.450061375Z[GMT]")

public class Workout {
  @SerializedName("startedAt")
  private Object startedAt = null;

  @SerializedName("finishedAt")
  private Object finishedAt = null;

  @SerializedName("restPeriod")
  private Object restPeriod = null;

  @SerializedName("exercises")
  private Object exercises = null;

  public Workout startedAt(Object startedAt) {
    this.startedAt = startedAt;
    return this;
  }

   /**
   * Date and time when the workout has been started
   * @return startedAt
  **/
  @Schema(description = "Date and time when the workout has been started")
  public Object getStartedAt() {
    return startedAt;
  }

  public void setStartedAt(Object startedAt) {
    this.startedAt = startedAt;
  }

  public Workout finishedAt(Object finishedAt) {
    this.finishedAt = finishedAt;
    return this;
  }

   /**
   * Date and time when the workout has been completed
   * @return finishedAt
  **/
  @Schema(description = "Date and time when the workout has been completed")
  public Object getFinishedAt() {
    return finishedAt;
  }

  public void setFinishedAt(Object finishedAt) {
    this.finishedAt = finishedAt;
  }

  public Workout restPeriod(Object restPeriod) {
    this.restPeriod = restPeriod;
    return this;
  }

   /**
   * Amount of seconds for rest between the exercises
   * @return restPeriod
  **/
  @Schema(description = "Amount of seconds for rest between the exercises")
  public Object getRestPeriod() {
    return restPeriod;
  }

  public void setRestPeriod(Object restPeriod) {
    this.restPeriod = restPeriod;
  }

  public Workout exercises(Object exercises) {
    this.exercises = exercises;
    return this;
  }

   /**
   * A set of actions performed to achieve athletic goals during this specific workout
   * @return exercises
  **/
  @Schema(description = "A set of actions performed to achieve athletic goals during this specific workout")
  public Object getExercises() {
    return exercises;
  }

  public void setExercises(Object exercises) {
    this.exercises = exercises;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Workout workout = (Workout) o;
    return Objects.equals(this.startedAt, workout.startedAt) &&
        Objects.equals(this.finishedAt, workout.finishedAt) &&
        Objects.equals(this.restPeriod, workout.restPeriod) &&
        Objects.equals(this.exercises, workout.exercises);
  }

  @Override
  public int hashCode() {
    return Objects.hash(startedAt, finishedAt, restPeriod, exercises);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Workout {\n");
    
    sb.append("    startedAt: ").append(toIndentedString(startedAt)).append("\n");
    sb.append("    finishedAt: ").append(toIndentedString(finishedAt)).append("\n");
    sb.append("    restPeriod: ").append(toIndentedString(restPeriod)).append("\n");
    sb.append("    exercises: ").append(toIndentedString(exercises)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
